### ISSUE TITLE
also include number of books read to match spec

### ISSUE THREAD

**Issue by baileypierson** [NDBaxi/pwp-capstones#2]
https://github.com/NDBaxi/pwp-capstones/blob/a27bf19c6004d2c101160838943f2f423bfc87df/CapstoneProject/TomeRater.py#L21

This repr function works perfectly well on its own, but in order to better match the expectations of the spec for this project, I would suggest returning the total number of books read as well

**Comment by NDBaxi** [comment]
Alright, got it. Thanks.
