### ISSUE TITLE
Review purpose of __eq__ function

### ISSUE THREAD

**Issue by baileypierson** [NDBaxi/pwp-capstones#3]
https://github.com/NDBaxi/pwp-capstones/blob/a27bf19c6004d2c101160838943f2f423bfc87df/CapstoneProject/TomeRater.py#L26-L28

While this code works, it is standard practice for __eq__  functions to return boolean values (ie. True or False). Not doing so makes it very difficult to use Boolean logic with this User object and would confuse other developers who use this package

**Comment by NDBaxi** [comment]
Good suggestion with regards to 'best practice' of using __eq__ dunder function. Noted and will remember.
