### ISSUE TITLE
Dangerous use of global variable

### ISSUE THREAD

**Issue by baileypierson** [NDBaxi/pwp-capstones#4]
https://github.com/NDBaxi/pwp-capstones/blob/a27bf19c6004d2c101160838943f2f423bfc87df/CapstoneProject/TomeRater.py#L34

This variable should be included within the get_average_rating function, as the new total rating value needs to be recomputed with each call–– this total value will not be reset to zero after each call to the function, which will likely result in incorrect calculations

**Comment by NDBaxi** [comment]
Yup, totally agree.....Good catch. Thanks and noted.
